# Generated by Django 6.1.1 on 2026-09-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Starting location', max_length=255)),
                ('pickup_location', models.CharField(help_text='First stop for loading', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Final destination for unloading', max_length=255)),
                ('current_cycle_used_hours', models.FloatField(default=0.0, help_text='Hours already used in 70h/8day cycle')),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_duration_hours', models.FloatField(default=0.0)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('days_count', models.IntegerField(default=1)),
                ('result_payload', models.JSONField(blank=True, default=dict, help_text='Full response containing route coordinates, stops, and ELD log sheets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='trips_trip_created_b7c7fb_idx')],
            },
        ),
    ]
